export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL_EMAIL = "SIGNUP_FAIL_EMAIL";
export const SIGNUP_FAIL_ZIPCODE = "SIGNUP_FAIL_ZIPCODE";
export const SIGNUP_RESET = "SIGNUP_RESET";