#!/bin/bash

echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > .env
echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
echo "REACT_APP_EXPRESS_LOCAL=$REACT_APP_EXPRESS_LOCAL" >> .env
echo "REACT_APP_EC2=$REACT_APP_EC2" >> .env